name: Track Repo
description: Request a new repo to be tracked
title: "[REPO] <title>"
labels: [track-repo,bug]
assignees:
  - timheuer
body:
- type: markdown
  attributes:
    value: |
      Be sure to check already tracked repos: https://tacticsview.azurewebsites.net/about
- type: input
  attributes:
    label: Repo URL
    description: Full path to the root repo to track
  validations:
    required: true