name: Deploy to tacticsview
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'
    - '**/translations.yaml'
  workflow_dispatch:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: tacticsview
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  PROJECT_PATH: TacticView.csproj
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
  DOTNET_MULTILEVEL_LOOKUP: 0
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 🧰 Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        dotnet-quality: preview

    - name: ♻️ Restore packages
      run: dotnet restore "${{ env.PROJECT_PATH }}" -r linux-x64
    - name: ⚒️ Build app
      run: dotnet build "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore /p:SourceRevisionId=${{ github.sha }} -r linux-x64 --self-contained
    - name: 🧪 Test app
      run: dotnet test "${{ env.PROJECT_PATH }}" --no-build
    - name: 🖨️ Publish app for deploy
      run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" -r linux-x64 --self-contained
    - name: ⬆️ Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  staging:
    needs: build
    name: Deploy to staging
    environment:
        name: staging
        url: ${{ steps.deploy_staging.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
    # Download artifacts
    - name: ⬇️ Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: webapp
    
        
    # Login to Azure
    - name: 🔐 Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    # Deploy to App Service Linux
    - name: 🎛️ Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      id: deploy_staging
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: staging
        package: .
        
    # Logout of Azure
    - name: 🔐 Azure Logout
      run: |
        az logout

  deploy:
    needs: staging
    environment:
      name: production
      url: ${{ steps.deploy_production.outputs.webapp-url }}
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
    # Download artifacts
    - name: ⬇️ Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: webapp

    # Login to Azure
    - name: 🔐 Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Deploy to App Service Linux
    - name: 🎛️ Deploy to Azure WebApp
      id: deploy_production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
        
    # Logout of Azure
    - name: 🔐 Azure Logout
      run: |
        az logout

  refresh-cache:
    needs: deploy
    name: Refresh cache
    runs-on: ubuntu-latest
    steps:
    - name: 🔃 Refresh cache
      run: curl https://tacticsview.azurewebsites.net/refresh-cache
