name: "Translations"

on:
  push:
    branches:
      - main
    paths:
    - '**.en.resx'

  workflow_dispatch:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
jobs:
  translate:
    name: Create Translations    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Use the resource translator to automatically translate resource files
    - name: Resource translator
      id: resource_translator
      uses: IEvangelist/resource-translator@v2.0.4
      with:
        subscriptionKey: ${{ secrets.AZURE_TRANSLATOR_SUBSCRIPTION_KEY }}
        endpoint: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
        region: ${{ secrets.AZURE_TRANSLATOR_REGION }}
        sourceLocale: 'en'

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.4.1
      with:
          commit-message: Updating translations
          title: '${{ steps.resource_translator.outputs.summary-title }}'
          body: '${{ steps.resource_translator.outputs.summary-details }}'